# Generated by Django 4.2.7 on 2026-04-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_trilha_options_trilha_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='tipo',
            field=models.CharField(default='trilha', max_length=30),
        ),
    ]
