# Generated by Django 4.2.7 on 2025-11-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('dificuldade', models.CharField(max_length=50)),
                ('distancia_km', models.FloatField()),
                ('descricao', models.TextField()),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parque')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parque')),
            ],
        ),
        migrations.CreateModel(
            name='Biodiversidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parque')),
            ],
        ),
    ]
