# Generated by Django 4.2.7 on 2025-11-17 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trilha',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AddField(
            model_name='trilha',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trilha',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trilha',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trilha',
            name='status',
            field=models.CharField(default='aberta', max_length=30),
        ),
        migrations.AddField(
            model_name='trilha',
            name='tempo_estimado_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='distancia_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='parque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to='api.parque'),
        ),
        migrations.CreateModel(
            name='TrilhaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='trilhas/fotos/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='api.trilha')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('nota', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.trilha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='api.trilha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('user', 'trilha')},
            },
        ),
    ]
